//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Painter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Painter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Painter.
        /// </summary>
        public static string APPLICATION_TITLE {
            get {
                return ResourceManager.GetString("APPLICATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception:.
        /// </summary>
        public static string LOG_HUE_BRIDGE_EXCEPTION {
            get {
                return ResourceManager.GetString("LOG_HUE_BRIDGE_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge says:.
        /// </summary>
        public static string LOG_HUE_BRIDGE_RESPONSE {
            get {
                return ResourceManager.GetString("LOG_HUE_BRIDGE_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue File.
        /// </summary>
        public static string MAIN_FILETYPE_DESCRIPTION {
            get {
                return ResourceManager.GetString("MAIN_FILETYPE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item selected..
        /// </summary>
        public static string MAIN_NO_ITEM_SELECTED {
            get {
                return ResourceManager.GetString("MAIN_NO_ITEM_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue.
        /// </summary>
        public static string MAIN_TABS_HUE {
            get {
                return ResourceManager.GetString("MAIN_TABS_HUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string MAIN_TABS_LOG {
            get {
                return ResourceManager.GetString("MAIN_TABS_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Preview.
        /// </summary>
        public static string MAIN_TABS_PREVIEW {
            get {
                return ResourceManager.GetString("MAIN_TABS_PREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling.
        /// </summary>
        public static string MAIN_TABS_SAMPLING {
            get {
                return ResourceManager.GetString("MAIN_TABS_SAMPLING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge IP.
        /// </summary>
        public static string TABHUE_BRIDGEIP {
            get {
                return ResourceManager.GetString("TABHUE_BRIDGEIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge username.
        /// </summary>
        public static string TABHUE_BRIDGEUSERNAME {
            get {
                return ResourceManager.GetString("TABHUE_BRIDGEUSERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string TABHUE_COLOURSET {
            get {
                return ResourceManager.GetString("TABHUE_COLOURSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string TABHUE_COLOURSET_A {
            get {
                return ResourceManager.GetString("TABHUE_COLOURSET_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string TABHUE_COLOURSET_B {
            get {
                return ResourceManager.GetString("TABHUE_COLOURSET_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        public static string TABHUE_COLOURSET_G {
            get {
                return ResourceManager.GetString("TABHUE_COLOURSET_G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string TABHUE_COLOURSET_R {
            get {
                return ResourceManager.GetString("TABHUE_COLOURSET_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string TABHUE_REGISTER {
            get {
                return ResourceManager.GetString("TABHUE_REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Colour.
        /// </summary>
        public static string TABHUE_SENDCOLOUR {
            get {
                return ResourceManager.GetString("TABHUE_SENDCOLOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Hue.
        /// </summary>
        public static string TABHUE_SENDTOHUE {
            get {
                return ResourceManager.GetString("TABHUE_SENDTOHUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition (x00ms).
        /// </summary>
        public static string TABHUE_TRANSITIONSPEED {
            get {
                return ResourceManager.GetString("TABHUE_TRANSITIONSPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable all form drawing - send to log only.
        /// </summary>
        public static string TABPREVIEW_DISABLEDRAWING {
            get {
                return ResourceManager.GetString("TABPREVIEW_DISABLEDRAWING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Colour.
        /// </summary>
        public static string TABPREVIEW_GETCOLOUR {
            get {
                return ResourceManager.GetString("TABPREVIEW_GETCOLOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grab Screen.
        /// </summary>
        public static string TABPREVIEW_GRABSCREEN {
            get {
                return ResourceManager.GetString("TABPREVIEW_GRABSCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show live preview when sampling.
        /// </summary>
        public static string TABPREVIEW_SHOWLIVEPREVIEW {
            get {
                return ResourceManager.GetString("TABPREVIEW_SHOWLIVEPREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Testcard.
        /// </summary>
        public static string TABPREVIEW_TESTCARD {
            get {
                return ResourceManager.GetString("TABPREVIEW_TESTCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conserve Memory.
        /// </summary>
        public static string TABSAMPLING_CONSERVEMEMORY {
            get {
                return ResourceManager.GetString("TABSAMPLING_CONSERVEMEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval (ms).
        /// </summary>
        public static string TABSAMPLING_INTERVAL {
            get {
                return ResourceManager.GetString("TABSAMPLING_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/O Config.
        /// </summary>
        public static string TABSAMPLING_IO {
            get {
                return ResourceManager.GetString("TABSAMPLING_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 source, 1 destination.
        /// </summary>
        public static string TABSAMPLING_IO_1_TO_1 {
            get {
                return ResourceManager.GetString("TABSAMPLING_IO_1_TO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 sources, 1 destination.
        /// </summary>
        public static string TABSAMPLING_IO_8_TO_1 {
            get {
                return ResourceManager.GetString("TABSAMPLING_IO_8_TO_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling Preset.
        /// </summary>
        public static string TABSAMPLING_PRESET {
            get {
                return ResourceManager.GetString("TABSAMPLING_PRESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick (Rough).
        /// </summary>
        public static string TABSAMPLING_PRESET_FAST {
            get {
                return ResourceManager.GetString("TABSAMPLING_PRESET_FAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow (Accurate).
        /// </summary>
        public static string TABSAMPLING_PRESET_SLOW {
            get {
                return ResourceManager.GetString("TABSAMPLING_PRESET_SLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Accuracy.
        /// </summary>
        public static string TABSAMPLING_SAMPLEACCURACY {
            get {
                return ResourceManager.GetString("TABSAMPLING_SAMPLEACCURACY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Width (%).
        /// </summary>
        public static string TABSAMPLING_SAMPLEWIDTH {
            get {
                return ResourceManager.GetString("TABSAMPLING_SAMPLEWIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string TABSAMPLING_START {
            get {
                return ResourceManager.GetString("TABSAMPLING_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should never see this....
        /// </summary>
        public static string TESTSTRING {
            get {
                return ResourceManager.GetString("TESTSTRING", resourceCulture);
            }
        }
    }
}
